#  /$$$$$$            /$$           /$$        /$$$$$$   /$$$$$$ 
# /$$__  $$          |__/          | $$       /$$__  $$ /$$__  $$
#| $$  \ $$ /$$   /$$ /$$  /$$$$$$$| $$   /$$| $$  \__/| $$  \__/
#| $$  | $$| $$  | $$| $$ /$$_____/| $$  /$$/|  $$$$$$ | $$ /$$$$
#| $$  | $$| $$  | $$| $$| $$      | $$$$$$/  \____  $$| $$|_  $$
#| $$/$$ $$| $$  | $$| $$| $$      | $$_  $$  /$$  \ $$| $$  \ $$
#|  $$$$$$/|  $$$$$$/| $$|  $$$$$$$| $$ \  $$|  $$$$$$/|  $$$$$$/
# \____ $$$ \______/ |__/ \_______/|__/  \__/ \______/  \______/ 
#      \__/                                          Simple Plugin made by Hadi & a8kj   



game-settings:
  